### ISSUE TITLE
音量调节问题

### ISSUE THREAD

**Issue by 9609759** [georgezhao2010/azure_cognitive_speech#1]
大佬，你好，我用了你的集成，感觉非常棒，唯一一个遗憾是，不知道如何调整音量，始终觉得声音偏小，不知道该如何真大音量。

**Comment by georgezhao2010** [comment]
> 大佬，你好，我用了你的集成，感觉非常棒，唯一一个遗憾是，不知道如何调整音量，始终觉得声音偏小，不知道该如何真大音量。

音量不是由回放设备控制吗？
