### ISSUE TITLE
Refresh token failed, reason: Access Denied

### ISSUE THREAD

**Issue by Eric9453** [georgezhao2010/azure_cognitive_speech#2]
update: 是我的帳戶出問題，token被系統取消 了

HA core: 2021.6.6
HACS: 1.14.0
azure_cognitive_speech:0.0.5

之前用起來都很順利，大概1周前開始無法使用，更新後也是如此
報錯如下：

自訂整合產生錯誤。

Logger: custom_components.azure_cognitive_speech.speech
Source: custom_components/azure_cognitive_speech/speech.py:28
Integration: azure_cognitive_speech (documentation, issues)
First occurred: 15:54:26 (5 occurrences)
Last logged: 15:55:42

Refresh token failed, reason: Access Denied

**Comment by georgezhao2010** [comment]
> update: 是我的帳戶出問題，token被系統取消 了
> 
> HA core: 2021.6.6
> HACS: 1.14.0

这个我提醒你一下，你Check一下Mail，Microsoft应该提醒过你要upgrade你的azure账户。

否则一个月就会被锁Token，upgrade时，记得所有那些一年收费多少钱的服务都不要选，就有1年免费可用。即使到了收费期，收费也很便宜。记得百万字符也就是100港币左右？
